src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Trick", inversedBy="comments", cascade={"persist"},fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $trick;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User",fetch="EAGER")
     * @ORM\JoinColumn()
     */
    private $user;


    public function __construct()
    {
        $this->creation_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Trick.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Cocur\Slugify\Slugify;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 */
class Trick
{
    const NIVEAU = [
      0 => "",
      1 => "Facile",
      2 => "Moyen",
      3 => "Difficile",
      4 => "Très difficile"
    ];

    const TRICK_GROUP = [
      0 => "",
      1 => "Les grabs",
      2 => "Les rotations",
      3 => "Les flips"
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreation;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trick", cascade={"persist","remove"})
     */
    private $comments;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 1,
     *      max = 4,
     *      minMessage = "Veuillez choisir un niveau de difficulté valide.",
     *      maxMessage = "Veuillez choisir un niveau de difficulté valide.",
     *
     * )
     */
    private $niveau;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 1,
     *      max = 3,
     *      minMessage = "Veuillez choisir un type de figure valide.",
     *      maxMessage = "Veuillez choisir un type de figure valide."
     * )
     */
    private $trick_group;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $imgDocs = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $videoDocs = [];

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $slugName;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->dateCreation = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }


    public function setName(string $name): self
    {
        $this->name = $name;
        $this->slugName = $this->createSlug($this->name);

        return $this;
    }

    public function getSlugName()
    {
        return $this->slugName;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }


    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function getNiveau()
    {
        return $this->niveau;
    }

    public function setNiveau($niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getTrickGroup()
    {
        return $this->trick_group;
    }

    public function setTrickGroup($trick_group): self
    {
        $this->trick_group = $trick_group;

        return $this;
    }

    public function getImgDocs(): ?array
    {
        return $this->imgDocs;
    }

    public function setImgDocs(?array $attachements): self
    {
        $this->imgDocs = $attachements;
  
        return $this;
    }
    public function addImgDoc(?string $attachement): self
    {
        $this->imgDocs[] = $attachement;

        return $this;
    }

    public function getVideoDocs(): ?array
    {
        return $this->videoDocs;
    }

    public function setVideoDocs(?array $videoDocs): self
    {
        $this->videoDocs = $videoDocs;

        return $this;
    }

    public function getFirstImg()
    {
        reset($this->imgDocs);
        return current($this->imgDocs);
    }

    private function createSlug($str, $delimiter = '-')
    {
        $slug = strtolower(trim(preg_replace('/[\s-]+/', $delimiter, preg_replace('/[^A-Za-z0-9-]+/', $delimiter, preg_replace('/[&]/', 'and', preg_replace('/[\']/', '', iconv('UTF-8', 'ASCII//TRANSLIT', $str))))), $delimiter));
        return $slug;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('niveau', ChoiceType::class, ['choices'=>array_flip(Trick::NIVEAU), 'label' => 'Niveau de difficulté'])
            ->add('trick_group', ChoiceType::class, ['choices'=>array_flip(Trick::TRICK_GROUP), 'label' => 'Type de figure'])
            ->add('imgDocs', CollectionType::class, [
               'entry_type' => FileType::class,
               'entry_options' => array(
                'constraints'  => array(
                  new File(['maxSize' => '2M',
                  "maxSizeMessage" => "Votre document ne doit pas dépasser les 2 Mo.",
                  "mimeTypes" => ["image/jpeg", "image/png"],
                  "mimeTypesMessage" => "Le document doit avoir une des extensions suivantes : jpeg, png, jpg.",
                        ]),
                   ),
                ),
               'prototype_name' => '__image__',
               'prototype'      => true,
               'allow_add'     => true,
               'allow_delete'   => true,
               'required' =>false,
               'label' => false,
               
            ])
            ->add('videoDocs', CollectionType::class, [
               'entry_type' => FileType::class,
               'entry_options' => array(
                'constraints'  => array(
                  new File(['maxSize' => '4M',
                  "maxSizeMessage" => "Votre video ne doit pas dépasser les 20 Mo.",
                  "mimeTypes" => [" video/x-msvideo", "video/mp4","video/ogg"],
                  "mimeTypesMessage" => "Le document doit avoir une des extensions suivantes : avi, mp4, ogg.",
                        ]),
                   ),
                ),
               'prototype_name' => '__video__',
               'prototype'      => true,
               'allow_add'     => true,
               'allow_delete'   => true,
               'required' =>false,
               'label' => false,
               
            ])

            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,

        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Trick;
use App\Form\TrickType;
use App\Repository\TrickRepository;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentsRepository;
use App\Entity\User;
use App\Repository\UserRepository;

use App\Service\UploadedFileManager;
use App\Service\TemporaryFileManager;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * handle all requests related to trick diplay and management
 */
class TrickController extends AbstractController
{
    private $uploadedFile;

    public function __construct(UploadedFileManager $uploadedFile)
    {
        $this->uploadedFile = $uploadedFile;
    }
    /**
     * Action : get home page
     * @Route("/", name="trick_index", methods={"GET"})
     */
    public function index(TrickRepository $trickRepository): Response
    {
        $tricks = $trickRepository->findAll();


        return $this->render('trick/index.html.twig', [
          'tricks' => $tricks,
            'fixed_menu'=> 'enabled'

        ]);
    }

    /**
     * Action : Create new trick
     * @Route("member/new", name="trick_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $trick->setVideoDocs($this->uploadedFile->docsInputManager($form->get('videoDocs')->getData()));
            $trick->setImgDocs($this->uploadedFile->docsInputManager($form->get('imgDocs')->getData()));


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($trick);
            $entityManager->flush();

            return $this->redirectToRoute('trick_index');
        }

        return $this->render('member/new.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }


    /**
     * Action : display a trick details page
     * @Route("/{slug}-{id}", name="trick_show", methods={"GET","POST"}, requirements= {"slug": "[a-z0-9\-]*"})
     */
    public function show(Trick $trick, Request $request, string $slug): Response
    {
        if ($trick->getSlugName() !== $slug) {
            return $this->redirectToRoute("trick_show", [
            'id' => $trick->getId(),
            'slug' => $trick->getSlugName()
          ], 301);
        }
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setTrick($trick);
            $comment->setUser($this->getUser());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            $comment = new Comment();
            $form = $this->createForm(CommentType::class, $comment);
        }

        $niveau = Trick::NIVEAU[$trick->getNiveau()];
        $trick_group = Trick::TRICK_GROUP[$trick->getTrickGroup()];

        return $this->render('trick/show.html.twig', [
          'comment'=> $comment,
          'form' => $form->createView(),
          'trick' => $trick,
          'niveau' => $niveau,
          'trick_group' => $trick_group
        ]);
    }


    /**
     * Action : Edit a trick
     * @Route("member/{id}/edit", name="trick_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Trick $trick, TemporaryFileManager $temporaryStorage): Response
    {
        $temporaryStorage->setTempImg($trick->getImgDocs());
        $temporaryStorage->setTempVideo($trick->getVideoDocs());

        $trick->setImgDocs($temporaryStorage->getTempImg());
        $trick->setVideoDocs($temporaryStorage->getTempVideo());

    
        $form = $this->createForm(TrickType::class, $trick);

        if ($request->isMethod('post')) {
            $storedImages = $temporaryStorage->getTempImg();
            $storedVideos = $temporaryStorage->getTempVideo();
        }

        $form->handleRequest($request);

       
        if ($form->isSubmitted() && $form->isValid()) {
            $trick =  $this->validateEdition($form, $trick, 'imgDocs', $storedImages);
            $trick = $this->validateEdition($form, $trick, 'videoDocs', $storedVideos);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($trick);
            $entityManager->flush();

            return $this->redirectToRoute('trick_index');
        }


        return $this->render('member/edit.html.twig', [

            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Action : delete a trick
     * @Route("member/{id}/delete", name="trick_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Trick $trick): Response
    {
        if ($this->isCsrfTokenValid('delete'.$trick->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($trick);
            $entityManager->flush();
        }

        return $this->redirectToRoute('trick_index');
    }

    /**
     * Action : ajax request to get or count tricks from the db
     * @Route("/ajax/", name="trick_ajax", methods={"POST"})
     */
    public function ajax(TrickRepository $trickRepository, Request $request)
    {
        if (!$request->request->has('first')) {
            return $this->render('trick/ajax.html.twig', [
          'count' => $trickRepository->countTricks()
        ]);
        } else {
            return $this->render('trick/ajax.html.twig', [

            'tricks' => $trickRepository->loadXtricks($request->request->get('first'), 4),
        ]);
        }
    }


    /**
     * Action : Ajax request: Add comments to trick details page
     * @Route("/new_comments/{id}", name="new_comments", methods={"POST"})
     */
    public function newComments(CommentsRepository $commentRepo, Request $request, Trick $trick)
    {
        if (null !== $request->request->get('first')) {
            return $this->render('trick/comments.html.twig', [

        'comments' => $commentRepo->findComments($trick->getId(), $request->request->get('first'))
            
        ]);
        }
 
        return $this->render('trick/comments.html.twig', [

        'comments' => $commentRepo->findComments($trick->getId()),
        'initial_load' => true
            
        ]);
    }
    /**
     * Action : check if  old files are associated to a trick
     *          before adding new files
     */
    private function validateEdition($form, $trick, $identifier, $array)
    {
        if ($form->get($identifier)->getData() == null && isset($array)) {
            $files2Save = $this->uploadedFile->docsInputManager($array);
            ($identifier == 'imgDocs')? $trick->setImgDocs($files2Save): $trick->setVideoDocs($files2Save);
        } else {
            $docs = $form->get($identifier)->getData();
            $files2Save = $this->uploadedFile->docsInputManager($docs);

            ($identifier == 'imgDocs')? $trick->setImgDocs($files2Save): $trick->setVideoDocs($files2Save);
        }

        return $trick;
    }
}

templates/trick/_form.html.twig
{{ form_start(form) }}
  
     <div class="container">
        
        <div >{{form_row(form.name)}}</div>
        
        <div>{{form_row(form.description)}}</div>   

        <div class="row">
          <div class="col-md-6">{{form_row(form.niveau)}}</div>
          <div class="col-md-6">{{form_row(form.trick_group)}}</div>
        </div>
        <div class="row">
          
          <div class="col-md-6">
            <ul id="img-fields-list"
            data-prototype="{{ form_widget(form.imgDocs.vars.prototype)|e }}"
            data-widget-tags="{{ '<li></li>'|e }}"
            data-widget-counter="{{ form.children|length }}">
          {% for doc in form.imgDocs %}
              <li>
                  {{ form_widget(doc) }}
                  {{ form_errors(doc) }}
              </li>
          {% endfor %}
          </ul>

          <button type="button"
            class="add-another-collection-img btn btn-info"
            data-list-selector="#img-fields-list">Ajouter une image </button>
          </div>
          
          <div class="col-md-6">
            <ul id="doc-fields-list"
            data-prototype="{{ form_widget(form.videoDocs.vars.prototype)|e }}"
            data-widget-tags="{{ '<li></li>'|e }}"
            data-widget-counter="{{ form.children|length }}">
          {% for doc in form.videoDocs %}
              <li>
                  {{ form_widget(doc) }}
                  {{ form_errors(doc) }}
              </li>
          {% endfor %}
          </ul>

          <button type="button"
            class="add-another-collection-video btn btn-info"
            data-list-selector="#doc-fields-list">Ajouter une vidéo </button>
          </div>
        </div>
      </div>

   
     
    <button class="btn btn-light-green btn-sm">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

templates/trick/ajax.html.twig
{% if not tricks|default %}

  {{count[0].count}}

{% else %}

{% for trick in tricks %}  
      <div class="col-12 col-md-6 col-lg-3 m-0 p-3">
         <div class="card">
          {% if trick.imgDocs is empty %}
            <img src="{{ asset('img/non-disponible.jpg') }}" class="card-img-top img-fluid" alt="...">
            {% else %}
            <img src="{{ asset('uploads/images/' ~ trick.imgDocs[0]) }}" class="card-img-top img-fluid" alt="...">
          {% endif%}
            <div class="card-body ajax-card">
              <a class="card-title" href="{{path('trick_show', {'slug' : trick.slugname, 'id' : trick.id})}}">{{ trick.name }} </a>
              <a href="{{path('trick_edit',{id: trick.id })}}">
              <i class="fas fa-pencil-alt"></i>
              </a>
              <form method="post" action="{{ path('trick_delete', {'id': trick.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
              <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
              <button id="trash-icon"><i class="far fa-trash-alt"></i></button>
              </form>
              
              </a>              
            </div>
          </div>  
      </div>
     {% endfor %}

{% endif %}

templates/trick/comments.html.twig
   
<div id="jq-com" {% if (comments|length == 5) %}class="more"{% endif%}>
    
      {% for comment in comments|slice(0,4) %}
       <div class="alert alert-success">
          {% if app.user.picture is defined %}
            {# if user has  no picture stored use default avaatr#}
            <img src="{{asset('uploads/images/'~ app.user.picture[0])}}" class="rounded-circle img-fluid" style="max-width: 40px;">
            {% else %}
            <img src="{{asset('img/avatar-user.jpg')}}" class="rounded-circle img-fluid" style="max-width: 40px;">
          {% endif %}

         <strong>{{comment.user.nickName}}</strong><i> à écrit le {{comment.creationDate|date("d-m-Y")}}</i> : <strong>{{comment.content}}</strong> 

       </div>

      {% endfor %}

  </div>
   
  {% if (comments|length == 5) and (initial_load is defined) %}
      <button class="btn btn-indigo" id="jq-plus">Plus</button>
  {% endif %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trick index{% endblock %}

{% block body %}

<section>

  <div class="container">
    <div>
      <div class="d-flex row justify-content-start mx-auto" id="jq-card">    
      </div>

      <div class="mx-auto text-center">
        <img src="{{ asset('img/loading_spinner.gif')}}" id="spin-img">
      </div>

    </div>
     
    <button class="btn btn-default" id ="js-scroll-down"><i class="fas fa-arrow-down ml-1"></i></button>
  </div>
</div>

  
</section>

{% endblock %}

{% block javascripts %}
<script type="text/javascript">

  $(document).ready(function(){
    
    $('#spin-img').hide()
    var tricks_count;

    // initial request to get the tricks'number from db
    $.post( "{{path('trick_ajax')}}")
      .done(function(count){  tricks_count = parseInt(count);})

    if (tricks_count == 0) {$('#js-scroll-down').hide();}

    $('#js-scroll-down').on('click', function(e){

      $('#spin-img').show()
      var appended_tricks = $('#jq-card > div >.card').length;
     
      $.post( "{{path('trick_ajax')}}", {first: appended_tricks})
        .done(function(tricks){
          $('#spin-img').hide()
          $('#jq-card').append(tricks);
          var total_tricks = $('#jq-card > div >.card').length;
          // if there is no more tricks in the db hide button
          if (total_tricks == tricks_count) {
            $('#js-scroll-down').hide();
          }   
        })
      // scroll page down whenever the loading button is clicked
      var n = $(document).height();
      $('html, body').animate({ scrollTop:  $('body').offset().top + n }, 'slow');
    });
  });
  </script>
{% endblock %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trick{% endblock %}

{% block body %} 
{% block cover %}{% endblock %}
<!-- Jumbotron -->
<div class="card card-image" style="background-image: url('{{ asset('uploads/images/' ~ trick.getFirstImg)}}'), url('{{ asset('img/non-disponible.jpg')}}');background-repeat: no-repeat; background-size: cover; background-position: center;">
  <div class="text-white text-center rgba-stylish-strong py-5 px-4">
    <div class="edit-delete-btn">
      <a href="{{ path('trick_edit', {'id': trick.id})}}" class="btn btn-warning btn-sm">edit</a>
      {{ include('member/_delete_form.html.twig') }}
    </div>
    <div class="py-5">

      <!-- Content -->
      <h2 class="h2 orange-text"><i class="fas fa-snowboarding"></i></h2>
      <h1 class="card-title h2 my-4 py-2">{{ trick.name }}</h1>

    </div>
  </div>
</div>
<!-- Jumbotron -->

<div class="docs-container row text-center"> 

 {% for file in trick.getImgDocs() %}
 <div class="col-sm-6 col-md-4 col-lg-3 m-0 p-3">
    <a><img src="{{ asset('uploads/images/' ~ file)}}" class="thumbnails-docs" data-toggle="modal" data-target="#modal{{(file|split('.')|first)}}"></a>


  <!--Modal: modalYT-->
  <div class="modal fade" id="modal{{(file|split('.')|first)}}" tabindex="-1" role="dialog" aria-labelledby="{{(file|split('.')|first)}}" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">

      <!--Content-->
      <div class="modal-content">

        <!--Body-->
        <div class="modal-body mb-0 p-0">

          <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
              <img src="{{ asset('uploads/images/' ~ file)}}" class="embed-responsive-item">
          </div>
        </div>

      </div>
      <!--/.Content-->

    </div>
  </div>
  <!--Modal: modalYT-->
 </div>
  {% endfor %}

  {% for file in trick.getVideoDocs() %}
 <div class="col-sm-6 col-md-4 col-lg-3 m-0 p-3">
    <a><img src="{{ asset('img/video-icon.jpg')}}" class="thumbnails-docs" data-toggle="modal" data-target="#modal{{(file|split('.')|first)}}"></a>


  <!--Modal: modalYT-->
  <div class="modal fade" id="modal{{(file|split('.')|first)}}" tabindex="-1" role="dialog" aria-labelledby="{{(file|split('.')|first)}}" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">

      <!--Content-->
      <div class="modal-content">

        <!--Body-->
        <div class="modal-body mb-0 p-0">

          <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">

            <video  class="embed-responsive-item" controls>
              <source src="{{ asset('uploads/images/' ~ file)}}" type="video/mp4" allowfullscreen>
            </video>

          </div>
        </div>

      </div>
      <!--/.Content-->

    </div>
  </div>
  <!--Modal: modalYT-->
 </div>
  {% endfor %}

</div>


<!-- Card -->
<div class="card card-cascade wider reverse">

  <!-- Card content -->
  <div class="card-body card-body-cascade text-center">

    <!-- Title -->
    <h4 class="card-title"><strong>Description</strong></h4>
    <!-- Text -->
    <p class="card-text">{{trick.description}}</p>
    <hr>
    <div class="trick-info-collapse">
      <p>
      <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#multiCollapseExample1" aria-expanded="false" aria-controls="multiCollapseExample2">Niveau</button>
      <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Catégorie</button>
      <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#multiCollapseExample3" aria-expanded="false" aria-controls="multiCollapseExample2">Date d'ajout</button>
    </p>
    <div class="row">
      <div class="col">
        <div class="collapse multi-collapse" id="multiCollapseExample1">
          <div class="card card-body alert alert-dark">
            {{niveau}}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="collapse multi-collapse" id="multiCollapseExample2">
          <div class="card card-body alert alert-dark">
            {{trick_group}}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="collapse multi-collapse" id="multiCollapseExample3">
          <div class="card card-body alert alert-dark">
            {{trick.datecreation|date('d/m/Y')}}
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>

</div>
<!-- Card -->

<!-- Comments input-->

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
<div class="comments-container">
  <div>
    {{form_start(form)}}

      <div class="comment-input text-center">
       {{form_widget(form.content, { 'attr': {'class': 'form-control'} })}}

       <button class="btn btn-indigo" id="jq-insert">Envoyer</button> 
      </div>
    {{form_end(form)}}
  </div>

  {% endif %}
<!-- Comments input-->


<!-- Comments Display-->
  <div id="comments_block" class="text-center">

    
  </div>
<!-- Comments Display-->
</div>

{% endblock %}

{% block javascripts %}

  <script type="text/javascript">
    
    $(document).ready(function(){
      $.post( "{{path('new_comments', {id:trick.id})}}")
        .done(function(comments){
          $('#comments_block').empty().append(comments);

          $('#jq-plus').on('click', function(){
        var number_com = $('#jq-com > div').length;
      $.post( "{{path('new_comments',{id:trick.id})}}", {first: number_com})
        .done(function(comms){
          $(comms).insertBefore("#jq-plus");
          if (!$(comms).hasClass("more")) {
              $("#jq-plus").hide();
          }
          // SI LE RESULTAT DE LA REQUETE EST VIDE OU QU IL Y A MOINS DE 3 TRICKS CACHER LE BUTTON

        })
        

    });
        }) 

      });

  </script>

{% endblock %}